### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by guranu** [Atmosphere-NX/hac2l#1]
When i try to compile it i get this error: Building nx_release
make[1]: Entering directory '/data/data/com.termux/files/home/hac2l/source'
/data/data/com.termux/files/home/hac2l/source/tool.mk:5: /data/data/com.termux/files/home/hac2l/source//../../libraries/config/templates/stratosphere.mk: No such file or directory
make[1]: *** No rule to make target '/data/data/com.termux/files/home/hac2l/source//../../libraries/config/templates/stratosphere.mk'.  Stop.
make[1]: Leaving directory '/data/data/com.termux/files/home/hac2l/source'
make: *** [Makefile:39: nx_release] Error 2

Anyone know why this happens?

**Comment by SciresM** [comment]
The repo needs to be inside the tools folder of the atmosphere repo right now.

**Comment by nozwock** [comment]
> The repo needs to be inside the tools folder of the atmosphere repo right now.

@SciresM As you said, I've put `hac2l` repo inside the `tools` dir of the [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere)  but it still doesn't workout.
Am I supposed to do something else aswell?

```
❯ make
Building nx_release
make[1]: Entering directory '/home/nozwock/hub/dev/clones/Atmosphere/emummc/tools/hac2l'
/home/nozwock/hub/dev/clones/Atmosphere/emummc/tools/hac2l/tool.mk:5: /home/nozwock/hub/dev/clones/Atmosphere/emummc/tools/hac2l//../../libraries/config/templates/stratosphere.mk: No such file or directory
make[1]: *** No rule to make target '/home/nozwock/hub/dev/clones/Atmosphere/emummc/tools/hac2l//../../libraries/config/templates/stratosphere.mk'.  Stop.
make[1]: Leaving directory '/home/nozwock/hub/dev/clones/Atmosphere/emummc/tools/hac2l'
make: *** [Makefile:39: nx_release] Error 2
```

Also what would you say about the current state of the tool? Is it preferred to use this now instead of `hactool`?
Thanks,

**Comment by SciresM** [comment]
You put it in atmosphere/emummc/tools, not atmosphere/tools.

I don't think it's preferred, but it *does* support some newer games that hactool doesn't.

**Comment by nozwock** [comment]
Thanks for the reply, that was quick.
I had simply searched the atmosphere repo for a `tools` dir, didn't realize it should be `atmosphere/tools`.

Now it's complaining about devkitpro but information regarding that is available in the README, so I'll try to make this work.

**Comment by SciresM** [comment]
Well, it shouldn't complain about devkitPro. Looking at your command, you're just doing make...you want to do e.g. `make win_x64_release` or `make linux_x64_release`.  @nozwock

**Comment by SciresM** [comment]
Also note that cross-compiling currently isn't sorted out, it always uses the native compilers, even though you need to specify the target. I'm aware this is a deficiency :)

**Comment by nozwock** [comment]
No luck unfortunately, I'm building on an arch distro.
```
❯ make linux_x64_release
make: *** No rule to make target 'linux_x64_release'.  Stop.
```

> **Edit:**

This was a mistake on my part; Just as SciresM said, this would work:
```
git clone https://github.com/Atmosphere-NX/Atmosphere
cd Atmosphere
mkdir tools
cd tools
git clone https://github.com/Atmosphere-NX/hac2l
cd hac2l
make linux_x64_release
```

**Comment by SciresM** [comment]
Hm. Reach out to me on discord? `SciresM#0524`

**Comment by nozwock** [comment]
Will do, thnx

**Comment by ghost** [comment]
`SciresM#0524`
I was trying to build on aarch64 termux
m i doing something wrong? 
```make linux_arm64_clang_release```

~/.../tools/hac2l $ uname -m
aarch64
~/.../tools/hac2l $ make linux_arm64_clang_release
Building linux_arm64_clang_release
make[1]: Entering directory '/data/data/com.termux/files/home/Atmosphere/tools/hac2l'
result_get_name.cpp
In file included from /data/data/com.termux/files/home/Atmosphere/libraries/libstratosphere/../libvapours/source/result/result_get_name.cpp:20:
In file included from /data/data/com.termux/files/home/Atmosphere/libraries/config//../libvapours/include/vapours.hpp:18:
In file included from /data/data/com.termux/files/home/Atmosphere/libraries/config//../libvapours/include/vapours/common.hpp:17:
In file included from /data/data/com.termux/files/home/Atmosphere/libraries/config//../libvapours/include/vapours/includes.hpp:25:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/cstdlib:85:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/stdlib.h:97:
In file included from /data/data/com.termux/files/usr/include/stdlib.h:34:
In file included from /data/data/com.termux/files/usr/include/malloc.h:30:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/stdio.h:107:
In file included from /data/data/com.termux/files/usr/include/stdio.h:42:
In file included from /data/data/com.termux/files/usr/include/sys/types.h:36:
/data/data/com.termux/files/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
make[3]: *** [/data/data/com.termux/files/home/Atmosphere/libraries/config//arch/arm64/base_rules:13: result_get_name.o] Error 1
make[2]: *** [/data/data/com.termux/files/home/Atmosphere/libraries/config//../libstratosphere/libstratosphere.mk:111: all] Error 2
make[1]: *** [/data/data/com.termux/files/home/Atmosphere/tools/hac2l/tool.mk:89: check_lib] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/Atmosphere/tools/hac2l'
make: *** [Makefile:45: linux_arm64_clang_release] Error 2

btw 
Thanks in Advance!

**Comment by SciresM** [comment]
That doesn't seem like an issue with ams, it's complaining about an internal include from stdlib not being present?

**Comment by ghost** [comment]
ohh too quick !
I don't understand what is that types.h stuff

**Comment by ghost** [comment]
i will look for the lib on Google and let you know if it succeed. Thanks for the quick reply!

**Comment by guranu** [comment]
> i will look for the lib on Google and let you know if it succeed. Thanks for the quick reply!

Did you find a way to fix it???

**Comment by ghost** [comment]
> 

what architecture u want to build one and it's Linux right?

**Comment by co-rei** [comment]
>

**Comment by ghost** [comment]
[hac2l](https://github.com/co-rei/reisu/blob/main/hac2l?raw=true)  here's a precompiled working on termux proot-distro

**Comment by ghost** [comment]
> > i will look for the lib on Google and let you know if it succeed. Thanks for the quick reply!
> 
> Did you find a way to fix it???

**Comment by guranu** [comment]
> [hac2l](https://github.com/co-rei/reisu/blob/main/hac2l?raw=true) here's a precompiled working on termux proot-distro

I get a "cannot execute binary file" error when i try to launch it.

**Comment by guranu** [comment]
> > 
> 
> what architecture u want to build one and it's Linux right?

arm64.

**Comment by ghost** [comment]
> 

install proot-distro and "Ubuntu" then binutils on it 
download this precomp binary give execute permission it should execute

**Comment by guranu** [comment]
> 

![Screenshot_20230324-173145_1](https://user-images.githubusercontent.com/103632948/227552952-f16faa88-a1ca-4c76-b901-30ae761c8edb.jpg)

**Comment by guranu** [comment]
> > 
> 
> install proot-distro and "Ubuntu" then binutils on it download this precomp binary give execute permission it should execute

![Screenshot_20230324-173145_1](https://user-images.githubusercontent.com/103632948/227553055-6a2087b0-f93d-45a1-92ed-b814f50e3aae.jpg)

**Comment by ghost** [comment]
![Screenshot_2023-03-24-20-08-43-71_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/81258355/227556060-fa1dfbb3-8cfc-4ef4-9c3f-c670684f7182.jpg)
idk what's wrong with your device
i this one here works for me also i sent the same binary to my friends and it works

**Comment by ghost** [comment]
> > > 
> > 
> > 
> > install proot-distro and "Ubuntu" then binutils on it download this precomp binary give execute permission it should execute
> 
> ![Screenshot_20230324-173145_1](https://user-images.githubusercontent.com/103632948/227553055-6a2087b0-f93d-45a1-92ed-b814f50e3aae.jpg)

Try to copy that on /home or /root and then give execution permission and try once it should work if u are also using aarch64=$(uname -m)

**Comment by guranu** [comment]
> > > > 
> > > 
> > > 
> > > install proot-distro and "Ubuntu" then binutils on it download this precomp binary give execute permission it should execute
> > 
> > 
> > ![Screenshot_20230324-173145_1](https://user-images.githubusercontent.com/103632948/227553055-6a2087b0-f93d-45a1-92ed-b814f50e3aae.jpg)
> 
> Try to copy that on /home or /root and then give execution permission and try once it should work if u are also using aarch64=$(uname -m)

Tried to move it to move it to /home and /root and it still didn't work.

**Comment by ghost** [comment]
i can't help after that try to build your own

**Comment by guranu** [comment]
Well if i try compile it myself i get a types.h error wich you also got and you still didn't tell me how to fix it.

**Comment by SciresM** [comment]
This is really not the place for this.
